### ISSUE TITLE
how to disable file { $logrotate::cron_hourly_file:  in hourly.pp 

### ISSUE THREAD

**Issue by den-is** [voxpupuli/puppet-logrotate#103]
I have one hourly job, but module fails because of absent file as described in https://github.com/voxpupuli/puppet-logrotate/pull/76 PR.
Because of that I have to keep old version of module v2.0.0

If there is way to disable this hourly_file in newer_version before above PR is merged and published?

**Comment by daqqad** [comment]
You could just replicate the fix manually in your environment. I doubt it will ever get merged since it has been over a year now.

**Comment by Dan33l** [comment]
hi @den-is 
A comment was added on the PR : 
> Seeems it got fixed via another pull request (#105).

Can you confirm ? 
If yes, we will close the issue.
If no, can you propose a PR ?
