### ISSUE TITLE
Missing tag and Puppet Forge release for 3.3.0

### ISSUE THREAD

**Issue by baurmatt** [voxpupuli/puppet-logrotate#120]
https://github.com/voxpupuli/puppet-logrotate/blob/master/CHANGELOG.md says there is an 3.3.0 version but there is no tag or Puppet Forge release.

**Comment by bastelfreak** [comment]
Hi @baurmatt, thanks for the hint, the release got somehow lost in action. I just tried to release 3.3.0 again and it failed: https://travis-ci.org/voxpupuli/puppet-logrotate/jobs/400885886. I will spin up a new release.

**Comment by bastelfreak** [comment]
@baurmatt after some more digging, https://forge.puppet.com/puppet/logrotate now has the original 3.3.0 release.

**Comment by baurmatt** [comment]
Thanks for the quick reaction! :)
