### ISSUE TITLE
hourly jobs do not take the logrotate config

### ISSUE THREAD

**Issue by itamarla** [voxpupuli/puppet-logrotate#14]
Hi,
I see that if I create hourly jobs, the hourly cron runs logrotate with the hourly dir.
It rotates the logs defined in the hourly jobs but does not take into affect the default config fed into the ::logrotate class.
maybe we should create a /etc/logrotate.d/hourly/logrotate_hourly.conf with all the config params and an include for the hourly dir? This way is I passed xz as a default compression it would stay that way for hourly jobs.
Another way would be to merge the default config to the specific config in the houry job and plant the default params that were not mentioned in the job into every hourly job.
Am I missing something here?

**Comment by robinbowes** [comment]
I must confess, I adopted this code as it was languishing with several PRs outstanding, but I've not delved into it in any detail.

Can you give an example of the problem you are encountering and perhaps an example of how you propose to fix it?

Thanks,

R.

**Comment by juniorsysadmin** [comment]
Closing due to no response.
