### ISSUE TITLE
Cut a new release (3.5.0) 

### ISSUE THREAD

**Issue by jaredledvina** [voxpupuli/puppet-logrotate#157]
Would it be possible to get a new release cut and pushed to Puppet Forge: https://github.com/voxpupuli/puppet-logrotate/compare/v3.4.0...HEAD ? 

## Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: 6.6.0
- Module version: 3.4.0

**Comment by pjonesIDBS** [comment]
A new release on forge would be good as the current version isn't compatible with puppetlabs-stdlib (v6.0.0).

**Comment by Dan33l** [comment]
A new version 4.0.0 is now relased #159
