### ISSUE TITLE
Logrotate rule ERB template should not take variables from the scope object

### ISSUE THREAD

**Issue by imriz** [voxpupuli/puppet-logrotate#37]
It should use `has_variable?` and `instance_variable_get` methods.
The reason is that the scope object has variables from _any_ scope, and this might add variable values from other `logrotate::rule` instances, depending on declaration/parsing order.

This is probably the same root cause for yo61/puppet-logrotate#22

**Comment by imriz** [comment]
To reproduce, add the following test to the `rule_spec.rb` spec file:
```
  context 'template should not inherit variables from other scopes' do
      let(:title) { 'foo' }
      let(:params) {
        {:path => '/var/log/foo.log',:ifempty => true}
      }
      let(:facts) {
        {
            :osfamily => 'RedHat',
            :operatingsystemmajrelease => 7
        }
      }
      it do
        should contain_file('/etc/logrotate.d/btmp').without_content(/ifempty/)
      end
  end
```

**Comment by natemccurdy** [comment]
This is likely the root cause of issue #13

**Comment by applewiskey** [comment]
@natemccurdy , definitely. Have the same issue.

Any chance on https://github.com/yo61/puppet-logrotate/pull/38 merged?
