### ISSUE TITLE
"su" and "su_owner" parameters are not accepted in "conf"

### ISSUE THREAD

**Issue by TexGG** [voxpupuli/puppet-logrotate#40]
### Affected Puppet, Ruby, OS and module versions/distributions
- Puppet: v3.8.7 (master) / v3.4.3 (client)
- Ruby: v1.8.7 (master) / v1.9.3p484 (client)
- Distribution: CetnOS 6.7 64bits (master) / Ubuntu 14.04.5 LTS (client)
- Module version: v1.4.0
### How to reproduce (e.g Puppet code you use)

If you follow the "su", "su_owner" and "su_group" parameters for "rule" and apply it to "conf", it will fail and produce errors :

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter su on Logrotate::Conf[/etc/logrotate.conf] at /etc/puppet/manifests/classes/linux_logrotate.pp:94 on node mynode.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter su_owner on Logrotate::Conf[/etc/logrotate.conf] at /etc/puppet/manifests/classes/linux_logrotate.pp:94 on node mynode.local
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
### What behaviour did you expect instead

It should accept the "su" and "su_owner" parameter, like "rule" set do.
### Any additional information you'd like to impart

if you remove the "su" parameter and change "su_owner" to "su_user", it will work. I have found the solution checking the "templates/etc/logrotate.conf.erb" file.

**Comment by Heidistein** [comment]
I believe this is implemented by PR #128

**Comment by jurim76** [comment]
Please fix documentation
module version: "3.4.0"

manifests/rule.pp 99 su_user
README.md 128 su_owner
