### ISSUE TITLE
Release a new version to the forge

### ISSUE THREAD

**Issue by edestecd** [voxpupuli/puppet-logrotate#46]
Can you release a new version of this module to the forge, now that we have xenial support?

**Comment by robinbowes** [comment]
That's not an unreasonable request :)

**Comment by rlaban** [comment]
Any actual plans for this yet?

**Comment by robinbowes** [comment]
I need to fix up the tests, and do a release but am sorely short of time at the moment.

**Comment by juniorsysadmin** [comment]
Done as part of #64
