### ISSUE TITLE
logrotate::conf[/etc/logrotate.conf]

### ISSUE THREAD

**Issue by samgne** [voxpupuli/puppet-logrotate#49]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.4.2
- Ruby: Puppet agent 4 packaged ruby
- Distribution: RHEL 7
- Module version: 1.3.0 (checked 1.4.0 as well)

### How to reproduce (e.g Puppet code you use)
```
if ($::osfamily == 'Redhat') {
    class { '::logrotate':
      config => {
        compress => true,    # compress rotated logs
        dateext  => true,    # rotate weekly normally
        maxsize  => '100M',  # also rotate if it gets big
      }
    }
  }
```

### What are you seeing
Maxsize is not a valid parameter for logorotate::conf but it is for logrotate::rule.

### What behaviour did you expect instead
Expected same parameters as rule.pp
### Output log
```Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Logrotate::Conf[/etc/logrotate.conf]: has no parameter named 'maxsize' on node <hostname>
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

### Any additional information you'd like to impart
Think logrotate::conf just needs parameter added.

**Comment by achermes** [comment]
This is actually a regression introduced by https://github.com/voxpupuli/puppet-logrotate/commit/ee311f235ac34e78c2fb2cdda043c3ad89bf2b3c
