### ISSUE TITLE
Deprecation warnings from newer stdlib

### ISSUE THREAD

**Issue by jearls** [voxpupuli/puppet-logrotate#54]
- Puppet: `4.x`
- Ruby: Any
- Distribution: Any
- Module version: `1.4.0`
    - STDLIB version: `>= 4.13.0`

### How to reproduce (e.g Puppet code you use)
Any invocation of `logrotate::rule` or `logrotate::conf`, if the `stdlib` version is greater than *4.12.0*

### What are you seeing
    $ puppet apply -t --noop -e 'logrotate::rule { "mcelog": path => "/var/log/mcelog" }'
    Info: Loading facts
    Warning: This method is deprecated, please use the stdlib validate_legacy function, with Pattern[]. There is further documentation for validate_legacy function in the README.
       (at /export/home/johnson.earls/.puppetlabs/etc/code/modules/stdlib/lib/puppet/functions/deprecation.rb:25:in `deprecation')

### What behaviour did you expect instead
Lack of warnings

### Output log
See above

### Any additional information you'd like to impart

Work-around is to restrict `stdlib` to <= 4.12.0 in `metadata.json`.

**Comment by robinbowes** [comment]
I'll probably address this by releasing a new version that requires Puppet 4 or above.

I'll create a new ticket for that, and review how best to do that.

R.

**Comment by juniorsysadmin** [comment]
Completed as part of #68
