### ISSUE TITLE
Support Ubuntu 16.04

### ISSUE THREAD

**Issue by llowder** [voxpupuli/puppet-logrotate#59]
### Affected Puppet, Ruby, OS and module versions/distributions

- Distribution: Ubuntu 16.04
- Module version: 1.4.0

This module should support Ubuntu 16.04. this can be with a simple change to defaults.pp to add the su line as it currently does for "trusty".

**Comment by llowder** [comment]
I see that in Master it already has code to do this, so closing. Hopefully a new release will be out soon that has that in place.

**Comment by bastelfreak** [comment]
Hi @llowder, we currently release a new version at https://github.com/voxpupuli/puppet-logrotate/pull/64

Can you test if that works for you on ubuntu16.04?

**Comment by cliff-wakefield** [comment]
This seems to want to remove 
`su root syslog`

From /etc/logrotate.conf

The logic looks ok, but it doesn't seem to work.

**Comment by bastelfreak** [comment]
Hi @cliff-wakefield, thanks for the feedback. Are you able to provide a fix for this?

**Comment by cliff-wakefield** [comment]
I have completed the fix @bastelfreak in pull request #80 it just needs reviewing and approving.

**Comment by bastelfreak** [comment]
Thanks @cliff-wakefield. I will close this issue and review the PR.
