### ISSUE TITLE
Remove old CHANGELOG or merge with CHANGELOG.md

### ISSUE THREAD

**Issue by rendhalver** [voxpupuli/puppet-logrotate#69]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:
- Ruby:
- Distribution:
- Module version:

## What are you seeing

Puppet forge is picking up the CHANGELOG file and ignoring the new CHANGELOG.md file so we are not seeing the changes listed in the new file.

**Comment by cliff-wakefield** [comment]
This addresses [Issue #69](https://github.com/voxpupuli/puppet-logrotate/issues/69)
