### ISSUE TITLE
Hourly jobs are broken since 2.0.0

### ISSUE THREAD

**Issue by tux-o-matic** [voxpupuli/puppet-logrotate#85]
A File resource in [hourly.pp](https://github.com/voxpupuli/puppet-logrotate/blob/v3.0.1/manifests/hourly.pp#L35) points to a file which has been removed in release 2.0.0.
The class hourly.pp is included if a rule as 'rotate_every' set to 'hour' or 'hourly.

**Comment by actatux** [comment]
Duplicate #76
