### ISSUE TITLE
parameter 'path' references an unresolved type 'Stdlib::UnixPath'

### ISSUE THREAD

**Issue by bp85** [voxpupuli/puppet-logrotate#95]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 4.8.2
- Ruby: 2.1.0p0
- Distribution: CentOS 7.2
- Module version: 3.0.0 and later 

## How to reproduce (e.g Puppet code you use)
```
logrotate::rule { 'sssd':
      path          => '/var/log/sssd/*.log',
      rotate        => 4,
      rotate_every  => 'week',
    }
```
## What are you seeing
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Logrotate::Rule[sssd]: parameter 'path' references an unresolved type 'Stdlib::UnixPath'
```
## What behaviour did you expect instead
run without errors

**Comment by juniorsysadmin** [comment]
@bp85 It looks like you're missing a recent version of stdlib, no?

**Comment by juniorsysadmin** [comment]
No response, closing
